### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by dhruvvarde** [sqlite-sync/SQLite-sync.com#30]
I have successfully sync the data and get all the data in the local SQLite database but when I add a new record in local and try to sync on the server at that time, the new data is not reflating in the server database.  Its creating one .dat file and the data is present in it in XML format.

So can you please help to solve this issue?

**Comment by sqlite-sync** [comment]
Can you share logs?

**Comment by dhruvvarde** [comment]
I have send the sync request to the server like this :

{"content":"<?xml version=\"1.0\" encoding=\"utf-8\"?><SyncData xmlns=\"urn:sync-schema\"><tab n=\"MergeIdentity\"><ins><\/ins><upd><r><Id><![CDATA[116]]><\/Id><TableId><![CDATA[9]]><\/TableId><SubscriberId><![CDATA[215005]]><\/SubscriberId><Rev><![CDATA[1]]><\/Rev><IdentityStart><![CDATA[90040]]><\/IdentityStart><IdentityEnd><![CDATA[95040]]><\/IdentityEnd><IdentityCurrent><![CDATA[90041]]><\/IdentityCurrent><RowId><![CDATA[A3B362DA-E084-4400-B583-E0B8546B212D]]><\/RowId><\/r><\/upd><\/tab><tab n=\"MergeSubscribers\"><ins><\/ins><upd><\/upd><\/tab><tab n=\"Users\"><ins><\/ins><upd><\/upd><\/tab><tab n=\"Documents\"><ins><r><docId><![CDATA[90041]]><\/docId><docName><![CDATA[test msg]]><\/docName><RowId><![CDATA[null]]><\/RowId><\/r><\/ins><upd><\/upd><\/tab><tab n=\"UserDocuments\"><ins><\/ins><upd><\/upd><\/tab><tab n=\"Test\"><ins><\/ins><upd><\/upd><\/tab><delete><\/delete><\/SyncData>","subscriber":"ffffffff-9aaa-6f72-ffff-ffff99d603a9","version":"3"}

**Comment by swaytz** [comment]
I face the same error when using the android client. Server to sqlite synchronization works fine but the sqlite to server synchronization throws a similar exception.

`02-Dec-2019 14:28:33.412 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [sqlite-sync-serlvet] in context with path [/SqliteSync] threw exception [java.lang.NullPointerException] with root cause
 java.lang.NullPointerException
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:598)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
	at SQLiteSyncCore.SyncServer.Synchronization.SyncService.ParseStatmentParameter(SyncService.java:1315)
	at SQLiteSyncCore.SyncServer.Synchronization.SyncService.PushInsertRecords(SyncService.java:1070)
	at SQLiteSyncCore.SyncServer.Synchronization.SyncService.PushTableData(SyncService.java:1009)
	at SQLiteSyncCore.SyncServer.Synchronization.SyncService.CommitChangesToDb(SyncService.java:933)
	at SQLiteSyncCore.SyncServer.Synchronization.SyncService.ReceiveData(SyncService.java:848)
	at com.sqlitesync.ws.SyncAPI3.RecieveChanges(SyncAPI3.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:501)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by IchoTolot** [comment]
Do you set TIMESTAMP_FORMAT?

**Comment by swaytz** [comment]
I have followed the documentation and the properties files has the following contents. Is there any other place to set the TIMESTAMP_FORMAT?

DB_ENGINE = mysql
DBURL = jdbc:mysql://localhost:3306/amplisync?rewriteBatchedStatements=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
DBUSER = ****
DBPASS = ****
DBDRIVER = com.mysql.cj.jdbc.Driver
DATE_FORMAT = yyyy-MM-dd HH:mm:ss
HISTORY_DAYS = 7
LOG_LEVEL = 4

**Comment by sqlite-sync** [comment]
You need to put it in sync.properties

DATE_FORMAT =yyyy-MM-dd HH:mm:ss
TIMESTAMP_FORMAT =yyyy-MM-dd HH:mm:ssZ

**Comment by swaytz** [comment]
Thank you very much.Adding the timestamp solved the problem.
